window.VERDANA_SPANISH_DATA={
lessons:[
{title:'Start: Begruessung und Hoeflichkeit',xp:20,content:'Trainiere Hola, Buenos dias, Gracias, Por favor und kurze Vorstellungsformen.'},
{title:'Ich und Verdana AG',xp:30,content:'Sage wer du bist, woher du kommst und dass du fuer Verdana AG arbeitest.'},
{title:'Kundenkontakt',xp:35,content:'Einfache Saetze fuer Erstkontakt, Bedarf, Fragen und naechste Schritte.'},
{title:'Meetings und Termine',xp:35,content:'Termine vereinbaren, verschieben, bestaetigen und Projektorte besprechen.'},
{title:'Produkte, Material und Qualitaet',xp:40,content:'Grundwortschatz zu Produkten, Materialien, Mustern, Farbe, Oberflaeche und Qualitaet.'},
{title:'Offerte, Lieferung und Projekt',xp:45,content:'Wortschatz fuer Angebot, Preis, Lieferzeit, Baustelle, Montage und Projektstatus.'}
],
dialogs:[
{title:'Erstkontakt Kunde',text:'Hola, soy de Verdana AG. Podemos hablar de su proyecto?'},
{title:'Meeting vereinbaren',text:'Buenos dias. Podemos organizar una reunion esta semana?'},
{title:'Produkt erklaeren',text:'Ofrecemos productos de alta calidad para su proyecto.'},
{title:'Lieferung klaeren',text:'La entrega esta prevista para la proxima semana.'},
{title:'Offerte senden',text:'Le enviaremos la oferta por correo electronico.'}
],
vocabulary:[
['Hallo','Hola','Basics','Hola, soy de Verdana AG.'],
['Guten Morgen','Buenos dias','Basics','Buenos dias, como esta?'],
['Guten Nachmittag','Buenas tardes','Basics','Buenas tardes, gracias por su tiempo.'],
['Guten Abend','Buenas noches','Basics','Buenas noches y hasta manana.'],
['Danke','Gracias','Basics','Gracias por su mensaje.'],
['Vielen Dank','Muchas gracias','Basics','Muchas gracias por la informacion.'],
['Bitte','Por favor','Basics','Un momento, por favor.'],
['Gern geschehen','De nada','Basics','De nada, estamos a su disposicion.'],
['Entschuldigung','Disculpe','Basics','Disculpe, tengo una pregunta.'],
['Ja','Si','Basics','Si, podemos ayudar.'],
['Nein','No','Basics','No, no es un problema.'],
['Vielleicht','Quizas','Basics','Quizas manana.'],
['Heute','Hoy','Zeit','Hoy tenemos una reunion.'],
['Morgen','Manana','Zeit','Manana enviamos la oferta.'],
['Gestern','Ayer','Zeit','Ayer hablamos con el cliente.'],
['Woche','Semana','Zeit','La entrega es esta semana.'],
['Monat','Mes','Zeit','El proyecto empieza este mes.'],
['Jahr','Ano','Zeit','Este ano queremos crecer.'],
['Uhrzeit','Hora','Zeit','A que hora es la reunion?'],
['Termin','Cita','Zeit','Tenemos una cita con el cliente.'],
['Ich','Yo','Basics','Yo trabajo en Verdana AG.'],
['Sie formell','Usted','Basics','Usted tiene una pregunta?'],
['Wir','Nosotros','Basics','Nosotros ofrecemos calidad.'],
['Unser','Nuestro','Basics','Nuestro equipo esta preparado.'],
['Firma','Empresa','Business','Verdana AG es una empresa suiza.'],
['Team','Equipo','Business','Nuestro equipo responde rapido.'],
['Kunde','Cliente','Business','El cliente necesita informacion.'],
['Partner','Socio','Business','El socio trabaja con nosotros.'],
['Lieferant','Proveedor','Business','El proveedor confirma la fecha.'],
['Kontakt','Contacto','Business','Tiene un contacto tecnico?'],
['Name','Nombre','Basics','Cual es su nombre?'],
['E-Mail','Correo electronico','Kommunikation','Le envio un correo electronico.'],
['Telefon','Telefono','Kommunikation','Podemos hablar por telefono?'],
['Nachricht','Mensaje','Kommunikation','Gracias por su mensaje.'],
['Antwort','Respuesta','Kommunikation','Esperamos su respuesta.'],
['Frage','Pregunta','Kommunikation','Tengo una pregunta.'],
['Information','Informacion','Kommunikation','Necesitamos mas informacion.'],
['Dokument','Documento','Kommunikation','Adjunto el documento.'],
['Datei','Archivo','Kommunikation','Puede enviar el archivo?'],
['Anhang','Adjunto','Kommunikation','El catalogo esta adjunto.'],
['Meeting','Reunion','Meeting','La reunion es a las diez.'],
['Agenda','Agenda','Meeting','La agenda tiene tres puntos.'],
['Protokoll','Acta','Meeting','Enviamos el acta despues.'],
['Teilnehmer','Participante','Meeting','Hay cuatro participantes.'],
['Besprechen','Hablar de','Meeting','Podemos hablar del proyecto?'],
['Vereinbaren','Organizar','Meeting','Podemos organizar una reunion?'],
['Bestaetigen','Confirmar','Meeting','Puede confirmar la cita?'],
['Verschieben','Posponer','Meeting','Tenemos que posponer la reunion.'],
['Projekt','Proyecto','Projekt','Donde esta el proyecto?'],
['Projektleiter','Jefe de proyecto','Projekt','El jefe de proyecto esta informado.'],
['Baustelle','Obra','Projekt','La obra esta en Madrid.'],
['Adresse','Direccion','Projekt','Cual es la direccion de la obra?'],
['Plan','Plano','Projekt','Necesitamos el plano actual.'],
['Mass','Medida','Projekt','Cuales son las medidas?'],
['Terminplan','Calendario','Projekt','El calendario es importante.'],
['Status','Estado','Projekt','Cual es el estado del proyecto?'],
['Produkt','Producto','Produkte','Este producto es de alta calidad.'],
['Material','Material','Produkte','Que material necesita?'],
['Muster','Muestra','Produkte','Podemos enviar una muestra.'],
['Farbe','Color','Produkte','Que color prefiere?'],
['Oberflaeche','Superficie','Produkte','La superficie es resistente.'],
['Dicke','Espesor','Produkte','El espesor es importante.'],
['Laenge','Longitud','Produkte','Necesitamos la longitud exacta.'],
['Breite','Anchura','Produkte','Cual es la anchura?'],
['Hoehe','Altura','Produkte','La altura es correcta.'],
['Gewicht','Peso','Produkte','El peso depende del material.'],
['Qualitaet','Calidad','Qualitaet','Ofrecemos alta calidad.'],
['Garantie','Garantia','Qualitaet','La garantia es de dos anos.'],
['Zertifikat','Certificado','Qualitaet','Tenemos el certificado.'],
['Norm','Norma','Qualitaet','El producto cumple la norma.'],
['Pruefung','Prueba','Qualitaet','La prueba fue positiva.'],
['Freigabe','Aprobacion','Qualitaet','Esperamos la aprobacion.'],
['Angebot','Oferta','Verkauf','Le enviaremos la oferta.'],
['Preis','Precio','Verkauf','El precio depende de la cantidad.'],
['Rabatt','Descuento','Verkauf','Podemos revisar el descuento.'],
['Bestellung','Pedido','Verkauf','Hemos recibido el pedido.'],
['Rechnung','Factura','Verkauf','La factura se envia por correo.'],
['Zahlung','Pago','Verkauf','El pago esta pendiente.'],
['Menge','Cantidad','Verkauf','Que cantidad necesita?'],
['Verfuegbarkeit','Disponibilidad','Verkauf','La disponibilidad es buena.'],
['Lieferung','Entrega','Logistik','La entrega llega manana.'],
['Lieferzeit','Plazo de entrega','Logistik','El plazo de entrega es corto.'],
['Transport','Transporte','Logistik','El transporte esta organizado.'],
['Lager','Almacen','Logistik','El producto esta en el almacen.'],
['Paket','Paquete','Logistik','El paquete esta preparado.'],
['Adresse Lieferung','Direccion de entrega','Logistik','Confirme la direccion de entrega.'],
['Spedition','Empresa de transporte','Logistik','La empresa de transporte confirma la hora.'],
['Montage','Montaje','Projekt','El montaje empieza el lunes.'],
['Problem','Problema','Support','Hay un problema tecnico.'],
['Loesung','Solucion','Support','Buscamos una solucion rapida.'],
['Hilfe','Ayuda','Support','Necesita ayuda?'],
['Dringend','Urgente','Support','El tema es urgente.'],
['Einfach','Facil','Basics','Es facil de entender.'],
['Schwierig','Dificil','Basics','Esta pregunta es dificil.'],
['Schnell','Rapido','Basics','Respondemos rapido.'],
['Langsam','Lento','Basics','Puede hablar mas lento?'],
['Wichtig','Importante','Business','La calidad es importante.'],
['Moeglich','Posible','Business','Es posible esta semana.'],
['Nicht moeglich','No es posible','Business','No es posible hoy.'],
['Verstehen','Entender','Basics','Entiendo la pregunta.'],
['Sprechen','Hablar','Basics','Hablo un poco de espanol.'],
['Senden','Enviar','Kommunikation','Voy a enviar la oferta.'],
['Erhalten','Recibir','Kommunikation','Hemos recibido su mensaje.']
]
};
